# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.5
    - name: Install kubebuilder
      run: |
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz -o /tmp/kb.tgz
        tar zxf /tmp/kb.tgz -C /tmp/
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1.3.1
      with:
        args: release --skip-sign
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KUBEBUILDER_ASSETS: /tmp/kubebuilder_2.3.1_linux_amd64/bin/

